--- Makefile	2015-10-17 15:26:15.772947000 +0100
+++ Makefile.new	2015-10-17 15:25:58.113333000 +0100
@@ -15,7 +15,8 @@
 LICENSE_FILE=	${WRKSRC}/LICENSE
 
 LIB_DEPENDS=	libwebkitgtk-1.0.so:${PORTSDIR}/www/webkit-gtk2
-RUN_DEPENDS=	dmenu:${PORTSDIR}/x11/dmenu
+RUN_DEPENDS=	dmenu:${PORTSDIR}/x11/dmenu \
+		xprop:${PORTSDIR}/x11/xprop
 
 USE_GNOME=	gtk20
 USE_XORG=	x11
